# configuration
# fill in the course details
 
courseName: "Quantum Computing, Cryptography and Machine Learning Lab"

# small title that is at the top of every page
subtitle: "11860 - Quantum Computing, Cryptography and Machine Learning Lab — Spring Semester 2024"

# baseurl is the same as the name of the repository
baseurl: /2024-Spring-11860

# url where the required reading is available to download
docsUrl: "https://www.amazon.com/_/dp/1492039683?tag=oreilly20-20" 

# url where the student's grading info is kept
gradingUrl: "" 


# change only if you know what you are doing
collections:
  syllabus:
    output: true
defaults:
  - scope:
      path: ""
      type: syllabus
    values:
      layout: unit
